import SwiftUI

/// Entry point for the XGSail Apple Watch companion. See this folder's
/// README.md for how to add this as a watchOS target to the Capacitor iOS
/// project (it is not generated by `cap sync`).
@main
struct XGSailWatchApp: App {
    @StateObject private var recorder = SessionRecorder()

    init() {
        WatchConnectivityClient.shared.activate()
    }

    var body: some Scene {
        WindowGroup {
            ContentView()
                .environmentObject(recorder)
                .task { await recorder.requestAuthorization() }
        }
    }
}
